//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fence.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageEntity
    {
        public int Id { get; set; }
        public Nullable<int> UserEntityId { get; set; }
        public string TextField { get; set; }
        public Nullable<int> LengthField { get; set; }
        public Nullable<System.DateTime> LeaveDate { get; set; }
        public Nullable<short> Stars { get; set; }
        public Nullable<bool> PaidMessage { get; set; }
    
        public virtual UserEntity UserEntity { get; set; }
    }
}
