
USE [master]
GO

/****** Object:  Database [UserAndMessages]    Script Date: 31.10.2018 18:14:01 ******/
CREATE DATABASE [UserAndMessages]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'UserAndMessages', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\UserAndMessages.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'UserAndMessages_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\UserAndMessages_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [UserAndMessages] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [UserAndMessages].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [UserAndMessages] SET ANSI_NULL_DEFAULT OFF
GO

ALTER DATABASE [UserAndMessages] SET ANSI_NULLS OFF
GO

ALTER DATABASE [UserAndMessages] SET ANSI_PADDING OFF
GO

ALTER DATABASE [UserAndMessages] SET ANSI_WARNINGS OFF
GO

ALTER DATABASE [UserAndMessages] SET ARITHABORT OFF
GO

ALTER DATABASE [UserAndMessages] SET AUTO_CLOSE OFF
GO

ALTER DATABASE [UserAndMessages] SET AUTO_SHRINK OFF
GO

ALTER DATABASE [UserAndMessages] SET AUTO_UPDATE_STATISTICS ON
GO

ALTER DATABASE [UserAndMessages] SET CURSOR_CLOSE_ON_COMMIT OFF
GO

ALTER DATABASE [UserAndMessages] SET CURSOR_DEFAULT  GLOBAL
GO

ALTER DATABASE [UserAndMessages] SET CONCAT_NULL_YIELDS_NULL OFF
GO

ALTER DATABASE [UserAndMessages] SET NUMERIC_ROUNDABORT OFF
GO

ALTER DATABASE [UserAndMessages] SET QUOTED_IDENTIFIER OFF
GO

ALTER DATABASE [UserAndMessages] SET RECURSIVE_TRIGGERS OFF
GO

ALTER DATABASE [UserAndMessages] SET  ENABLE_BROKER
GO

ALTER DATABASE [UserAndMessages] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO

ALTER DATABASE [UserAndMessages] SET DATE_CORRELATION_OPTIMIZATION OFF
GO

ALTER DATABASE [UserAndMessages] SET TRUSTWORTHY OFF
GO

ALTER DATABASE [UserAndMessages] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO

ALTER DATABASE [UserAndMessages] SET PARAMETERIZATION SIMPLE
GO

ALTER DATABASE [UserAndMessages] SET READ_COMMITTED_SNAPSHOT OFF
GO

ALTER DATABASE [UserAndMessages] SET HONOR_BROKER_PRIORITY OFF
GO

ALTER DATABASE [UserAndMessages] SET RECOVERY FULL
GO

ALTER DATABASE [UserAndMessages] SET  MULTI_USER
GO

ALTER DATABASE [UserAndMessages] SET PAGE_VERIFY CHECKSUM
GO

ALTER DATABASE [UserAndMessages] SET DB_CHAINING OFF
GO

ALTER DATABASE [UserAndMessages] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF )
GO

ALTER DATABASE [UserAndMessages] SET TARGET_RECOVERY_TIME = 60 SECONDS
GO

ALTER DATABASE [UserAndMessages] SET DELAYED_DURABILITY = DISABLED
GO

EXEC sys.sp_db_vardecimal_storage_format N'UserAndMessages', N'ON'
GO

ALTER DATABASE [UserAndMessages] SET QUERY_STORE = OFF
GO

USE [UserAndMessages]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

USE [UserAndMessages]
GO

/****** Object:  Table [dbo].[MessageEntity]    Script Date: 31.10.2018 18:14:01 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  Table [dbo].[UserEntity]    Script Date: 31.10.2018 18:14:02 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  StoredProcedure [dbo].[CreateMessage]    Script Date: 31.10.2018 18:14:02 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  StoredProcedure [dbo].[CreateUser]    Script Date: 31.10.2018 18:14:02 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  StoredProcedure [dbo].[DeleteMessageEntity]    Script Date: 31.10.2018 18:14:02 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  StoredProcedure [dbo].[DeleteUserEntity]    Script Date: 31.10.2018 18:14:02 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  StoredProcedure [dbo].[GetAllMessages]    Script Date: 31.10.2018 18:14:02 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  StoredProcedure [dbo].[GetAllUserMessages]    Script Date: 31.10.2018 18:14:02 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  StoredProcedure [dbo].[GetAllUsers]    Script Date: 31.10.2018 18:14:02 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  StoredProcedure [dbo].[GetMessageById]    Script Date: 31.10.2018 18:14:02 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  StoredProcedure [dbo].[GetUserById]    Script Date: 31.10.2018 18:14:02 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  StoredProcedure [dbo].[UpdateMessageEntity]    Script Date: 31.10.2018 18:14:02 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/****** Object:  StoredProcedure [dbo].[UpdateUserEntity]    Script Date: 31.10.2018 18:14:02 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

USE [master]
GO

ALTER DATABASE [UserAndMessages] SET  READ_WRITE
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;

GO

--Syntax Error: Incorrect syntax near IDENTITY_CACHE.
--ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;



GO
